import 'package:flutter/material.dart';
import 'legal_document_screen.dart';

/// TODO: replace this placeholder text with your actual, lawyer-reviewed
/// Privacy Policy before shipping — this is illustrative structure
/// only, not real legal content.
class PrivacyPolicyScreen extends StatelessWidget {
  const PrivacyPolicyScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return const LegalDocumentScreen(
      title: 'Privacy policy',
      lastUpdated: '1 January 2026',
      sections: [
        LegalSection(
          heading: 'Information we collect',
          body: 'We collect information you provide directly, such as your name, contact details, and identity documents, along with information generated by your use of Zelyo, such as transaction history and device data.',
        ),
        LegalSection(
          heading: 'How we use your information',
          body: 'We use your information to provide and secure Zelyo\'s services, verify your identity, process transactions, comply with legal obligations, and communicate with you.',
        ),
        LegalSection(
          heading: 'Biometric data',
          body: 'Selfie and face-scan data collected during identity verification is used solely to confirm you are who you say you are, and is handled according to applicable data protection law.',
        ),
        LegalSection(
          heading: 'Sharing your information',
          body: 'We share information with banking partners, payment processors, and regulators as necessary to provide our services and meet legal requirements. We do not sell your personal data.',
        ),
        LegalSection(
          heading: 'Data security',
          body: 'We use encryption, access controls, and other safeguards to protect your information, including PIN- and biometric-protected access to sensitive actions within the app.',
        ),
        LegalSection(
          heading: 'Your rights',
          body: 'Depending on where you live, you may have rights to access, correct, or request deletion of your personal data. You can reach out via Contact support to exercise these rights.',
        ),
        LegalSection(
          heading: 'Data retention',
          body: 'We retain your information for as long as your account is active and as required to meet legal, regulatory, and accounting obligations.',
        ),
        LegalSection(
          heading: 'Changes to this policy',
          body: 'We may update this policy periodically. We\'ll notify you of material changes through the app.',
        ),
        LegalSection(
          heading: 'Contact',
          body: 'Questions about this policy can be directed to our support team from within the app.',
        ),
      ],
    );
  }
}